export interface SqlKeyword {
  label: string;
  detail: string;
}

export const SQL_KEYWORDS: SqlKeyword[] = [
  { label: "SELECT", detail: "Select columns" },
  { label: "FROM", detail: "Source table" },
  { label: "WHERE", detail: "Filter rows" },
  { label: "JOIN", detail: "Inner join" },
  { label: "INNER JOIN", detail: "Inner join" },
  { label: "LEFT JOIN", detail: "Left outer join" },
  { label: "RIGHT JOIN", detail: "Right outer join" },
  { label: "FULL JOIN", detail: "Full outer join" },
  { label: "CROSS JOIN", detail: "Cross join" },
  { label: "ON", detail: "Join condition" },
  { label: "GROUP BY", detail: "Group rows" },
  { label: "ORDER BY", detail: "Sort rows" },
  { label: "HAVING", detail: "Filter groups" },
  { label: "INSERT INTO", detail: "Insert rows" },
  { label: "UPDATE", detail: "Update rows" },
  { label: "DELETE FROM", detail: "Delete rows" },
  { label: "SET", detail: "Assign values" },
  { label: "VALUES", detail: "Value list" },
  { label: "CREATE", detail: "Create object" },
  { label: "ALTER", detail: "Alter object" },
  { label: "DROP", detail: "Drop object" },
  { label: "TRUNCATE", detail: "Truncate table" },
  { label: "INDEX", detail: "Index" },
  { label: "TABLE", detail: "Table" },
  { label: "VIEW", detail: "View" },
  { label: "SCHEMA", detail: "Schema" },
  { label: "DATABASE", detail: "Database" },
  { label: "AS", detail: "Alias" },
  { label: "AND", detail: "Logical AND" },
  { label: "OR", detail: "Logical OR" },
  { label: "NOT", detail: "Logical NOT" },
  { label: "IN", detail: "In list" },
  { label: "EXISTS", detail: "Exists check" },
  { label: "BETWEEN", detail: "Range check" },
  { label: "LIKE", detail: "Pattern match" },
  { label: "ILIKE", detail: "Case-insensitive pattern match" },
  { label: "IS NULL", detail: "Null check" },
  { label: "IS NOT NULL", detail: "Not null check" },
  { label: "CASE", detail: "Case expression" },
  { label: "WHEN", detail: "When clause" },
  { label: "THEN", detail: "Then clause" },
  { label: "ELSE", detail: "Else clause" },
  { label: "END", detail: "End block" },
  { label: "DISTINCT", detail: "Unique values" },
  { label: "ALL", detail: "All rows" },
  { label: "UNION", detail: "Union results" },
  { label: "UNION ALL", detail: "Union all results" },
  { label: "INTERSECT", detail: "Intersect results" },
  { label: "EXCEPT", detail: "Except results" },
  { label: "LIMIT", detail: "Limit rows" },
  { label: "OFFSET", detail: "Skip rows" },
  { label: "FETCH", detail: "Fetch rows" },
  { label: "ASC", detail: "Ascending" },
  { label: "DESC", detail: "Descending" },
  { label: "NULLS FIRST", detail: "Nulls first" },
  { label: "NULLS LAST", detail: "Nulls last" },
  { label: "WITH", detail: "CTE" },
  { label: "RECURSIVE", detail: "Recursive CTE" },
  { label: "RETURNING", detail: "Return affected rows" },
  { label: "CONFLICT", detail: "On conflict" },
  { label: "DO NOTHING", detail: "Do nothing" },
  { label: "DO UPDATE", detail: "Do update" },
  { label: "LATERAL", detail: "Lateral join" },
  { label: "OVER", detail: "Window function" },
  { label: "PARTITION BY", detail: "Window partition" },
  { label: "ROWS", detail: "Window frame" },
  { label: "RANGE", detail: "Window frame" },
  { label: "COALESCE", detail: "First non-null" },
  { label: "NULLIF", detail: "Null if equal" },
  { label: "CAST", detail: "Type cast" },
  { label: "EXTRACT", detail: "Extract date part" },
  { label: "COUNT", detail: "Count rows" },
  { label: "SUM", detail: "Sum values" },
  { label: "AVG", detail: "Average" },
  { label: "MIN", detail: "Minimum" },
  { label: "MAX", detail: "Maximum" },
  { label: "TRUE", detail: "Boolean true" },
  { label: "FALSE", detail: "Boolean false" },
  { label: "NULL", detail: "Null value" },
];
