CREATE SCHEMA IF NOT EXISTS lab;

CREATE TABLE lab.seed_manifest (
    id int PRIMARY KEY,
    document jsonb NOT NULL,
    loaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE lab.categories (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL
);

CREATE TABLE lab.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku text NOT NULL UNIQUE,
    name text NOT NULL,
    category_id int NOT NULL REFERENCES lab.categories (id),
    price_cents int NOT NULL,
    attributes jsonb NOT NULL
);

CREATE TABLE lab.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    full_name text NOT NULL,
    city text NOT NULL,
    profile jsonb NOT NULL
);

CREATE TABLE lab.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES lab.customers (id),
    status text NOT NULL,
    total_cents bigint NOT NULL,
    placed_at timestamptz NOT NULL,
    meta jsonb NOT NULL
);

CREATE TABLE lab.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES lab.orders (id),
    product_id bigint NOT NULL REFERENCES lab.products (id),
    quantity int NOT NULL,
    unit_price_cents int NOT NULL
);

CREATE TABLE lab.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    payload jsonb NOT NULL,
    occurred_at timestamptz NOT NULL
);

CREATE INDEX lab_orders_customer_idx ON lab.orders (customer_id);
CREATE INDEX lab_orders_status_idx ON lab.orders (status);
CREATE INDEX lab_order_items_order_idx ON lab.order_items (order_id);
CREATE INDEX lab_events_type_idx ON lab.events (event_type);
CREATE INDEX lab_events_payload_idx ON lab.events USING gin (payload);
