use crate::domain::connection::DriverType;
use crate::domain::schema::{CheckConstraint, ForeignKey, IndexOrigin, TableInfo, Trigger};

struct ForeignKeyDdlGroup<'a> {
    name: &'a str,
    from_columns: Vec<&'a str>,
    to_table: &'a str,
    to_columns: Vec<&'a str>,
    to_schema: &'a str,
    on_update: &'a str,
    on_delete: &'a str,
    match_option: &'a str,
    deferrable: bool,
    initially_deferred: bool,
}

pub(super) fn build_create_table_ddl(
    info: &TableInfo,
    driver: DriverType,
    check_constraints: &[CheckConstraint],
) -> String {
    let qualified = qualify_name_for_driver(driver, &info.table.schema, &info.table.name);
    let foreign_keys = group_foreign_keys_for_ddl(&info.foreign_keys);
    let definitions = table_definitions(info, driver, check_constraints, &foreign_keys);
    let mut ddl = format!("CREATE TABLE {qualified} (\n{}\n);\n", definitions.join(",\n"));

    append_index_ddl(&mut ddl, info, driver);
    if driver == DriverType::Postgres {
        append_postgres_foreign_keys(&mut ddl, &qualified, &foreign_keys);
    }

    ddl
}

pub(super) fn format_trigger_ddl(trigger: &Trigger) -> String {
    // SQLite: definition is the full CREATE TRIGGER SQL from sqlite_master.
    // PostgreSQL: definition is action_statement (EXECUTE FUNCTION ...),
    //   so emit the function definition first, then the CREATE TRIGGER.
    if trigger.definition.to_ascii_uppercase().starts_with("CREATE TRIGGER") {
        format!("{};\n", trigger.definition)
    } else {
        let qualified = qualify_name(&trigger.schema, &trigger.table_name);
        let trigger_stmt = format!(
            "CREATE TRIGGER {}\n  {} {} ON {}\n  {};\n",
            quote_identifier(&trigger.name),
            trigger.timing,
            trigger.event,
            qualified,
            trigger.definition
        );
        if !trigger.function_def.is_empty() {
            let mut ddl = String::new();
            ddl.push_str(&trigger.function_def);
            if !trigger.function_def.ends_with('\n') {
                ddl.push('\n');
            }
            ddl.push('\n');
            ddl.push_str(&trigger_stmt);
            ddl
        } else {
            trigger_stmt
        }
    }
}

fn group_foreign_keys_for_ddl(foreign_keys: &[ForeignKey]) -> Vec<ForeignKeyDdlGroup<'_>> {
    foreign_keys
        .iter()
        .map(|fk| ForeignKeyDdlGroup {
            name: &fk.name,
            from_columns: fk.from_columns.iter().map(|s| s.as_str()).collect(),
            to_table: &fk.to_table,
            to_columns: fk.to_columns.iter().map(|s| s.as_str()).collect(),
            to_schema: &fk.to_schema,
            on_update: &fk.on_update,
            on_delete: &fk.on_delete,
            match_option: &fk.match_option,
            deferrable: fk.deferrable,
            initially_deferred: fk.initially_deferred,
        })
        .collect()
}

fn qualify_name(schema: &str, name: &str) -> String {
    if schema.is_empty() {
        quote_identifier(name)
    } else {
        format!("{}.{}", quote_identifier(schema), quote_identifier(name))
    }
}

fn table_definitions(
    info: &TableInfo,
    driver: DriverType,
    check_constraints: &[CheckConstraint],
    foreign_keys: &[ForeignKeyDdlGroup<'_>],
) -> Vec<String> {
    let mut definitions: Vec<_> = info.columns.iter().map(format_column_definition).collect();

    if let Some(ref pk) = info.primary_key {
        definitions.push(format!(
            "    PRIMARY KEY ({})",
            quote_columns(&pk.columns.iter().map(String::as_str).collect::<Vec<_>>())
        ));
    }
    definitions.extend(check_constraints.iter().map(format_check_constraint));

    if driver == DriverType::SQLite {
        definitions.extend(foreign_keys.iter().map(format_sqlite_foreign_key));
        definitions.extend(
            info.indexes
                .iter()
                .filter(|index| index.origin == IndexOrigin::UniqueConstraint)
                .map(format_sqlite_unique_constraint),
        );
    }

    definitions
}

fn format_column_definition(column: &crate::domain::schema::Column) -> String {
    let mut definition = format!("    {} {}", quote_identifier(&column.name), column.data_type);
    if column.is_identity {
        definition.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    } else if column.is_generated {
        if let Some(ref expression) = column.default {
            definition.push_str(&format!(" GENERATED ALWAYS AS ({expression}) STORED"));
        }
    }
    if !column.nullable {
        definition.push_str(" NOT NULL");
    }
    if !column.is_identity && !column.is_generated {
        if let Some(ref default) = column.default {
            definition.push_str(&format!(" DEFAULT {default}"));
        }
    }
    definition
}

fn format_check_constraint(constraint: &CheckConstraint) -> String {
    format!(
        "    CONSTRAINT {} {}",
        quote_identifier(&constraint.name),
        check_constraint_definition(constraint),
    )
}

fn format_sqlite_foreign_key(foreign_key: &ForeignKeyDdlGroup<'_>) -> String {
    let to_qualified = qualify_name_for_driver(DriverType::SQLite, foreign_key.to_schema, foreign_key.to_table);
    let from_columns = quote_columns(&foreign_key.from_columns);
    let to_columns = quote_columns(&foreign_key.to_columns);
    let actions = format_foreign_key_actions(foreign_key);
    format!(
        "    CONSTRAINT {} FOREIGN KEY ({from_columns}) REFERENCES {to_qualified} ({to_columns}){actions}",
        quote_identifier(foreign_key.name),
    )
}

fn format_foreign_key_actions(foreign_key: &ForeignKeyDdlGroup<'_>) -> String {
    let mut clauses = String::new();
    if !foreign_key.match_option.is_empty()
        && foreign_key.match_option != "SIMPLE"
        && foreign_key.match_option != "NONE"
    {
        clauses.push_str(&format!(" MATCH {}", foreign_key.match_option));
    }
    if !foreign_key.on_update.is_empty() && foreign_key.on_update != "NO ACTION" {
        clauses.push_str(&format!(" ON UPDATE {}", foreign_key.on_update));
    }
    if !foreign_key.on_delete.is_empty() && foreign_key.on_delete != "NO ACTION" {
        clauses.push_str(&format!(" ON DELETE {}", foreign_key.on_delete));
    }
    if foreign_key.deferrable {
        clauses.push_str(" DEFERRABLE");
        if foreign_key.initially_deferred {
            clauses.push_str(" INITIALLY DEFERRED");
        }
    }
    clauses
}

fn format_sqlite_unique_constraint(index: &crate::domain::schema::Index) -> String {
    let columns = quote_columns(&index.columns.iter().map(String::as_str).collect::<Vec<_>>());
    format!("    UNIQUE ({columns})")
}

fn append_index_ddl(ddl: &mut String, info: &TableInfo, driver: DriverType) {
    let index_target = qualify_name_for_driver(driver, &info.table.schema, &info.table.name);
    for index in &info.indexes {
        if index.primary || (driver == DriverType::SQLite && index.origin == IndexOrigin::UniqueConstraint) {
            continue;
        }
        if driver == DriverType::Postgres && !index.definition.is_empty() {
            ddl.push_str(&index.definition);
            ddl.push_str(";\n");
            continue;
        }
        let unique = if index.unique { "UNIQUE " } else { "" };
        let index_name = qualify_name_for_driver(driver, &index.schema, &index.name);
        let cols = quote_columns(&index.columns.iter().map(String::as_str).collect::<Vec<_>>());
        ddl.push_str(&format!(
            "CREATE {unique}INDEX {index_name} ON {index_target} ({cols});\n"
        ));
    }
}

fn append_postgres_foreign_keys(ddl: &mut String, qualified_table: &str, foreign_keys: &[ForeignKeyDdlGroup<'_>]) {
    for foreign_key in foreign_keys {
        let to_qualified = qualify_name(foreign_key.to_schema, foreign_key.to_table);
        let from_columns = quote_columns(&foreign_key.from_columns);
        let to_columns = quote_columns(&foreign_key.to_columns);
        ddl.push_str(&format!(
            "ALTER TABLE {qualified_table} ADD CONSTRAINT {} FOREIGN KEY ({from_columns}) REFERENCES {to_qualified} ({to_columns}){};\n",
            quote_identifier(foreign_key.name),
            format_foreign_key_actions(foreign_key),
        ));
    }
}

fn qualify_name_for_driver(driver: DriverType, schema: &str, name: &str) -> String {
    if driver == DriverType::SQLite {
        quote_identifier(name)
    } else {
        qualify_name(schema, name)
    }
}

fn quote_columns(columns: &[&str]) -> String {
    columns
        .iter()
        .map(|column| quote_identifier(column))
        .collect::<Vec<_>>()
        .join(", ")
}

fn check_constraint_definition(constraint: &CheckConstraint) -> String {
    if constraint
        .definition
        .trim_start()
        .to_ascii_uppercase()
        .starts_with("CHECK")
    {
        constraint.definition.clone()
    } else {
        format!("CHECK ({})", constraint.definition)
    }
}

pub(super) fn quote_identifier(name: &str) -> String {
    let escaped = name.replace('"', "\"\"");
    format!("\"{escaped}\"")
}
